"""Generate the allocation-free C++ Hipparcos catalog in static storage."""

from __future__ import annotations

import struct
from pathlib import Path

import numpy as np


MAGIC = b"STRCAT01"
HEADER_FORMAT = "<8sII"
RECORD_DTYPE = np.dtype(
    [
        ("star_id", "<u4"),
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("vmag", "<f4"),
    ],
    align=False,
)

SUITE_ROOT = Path(__file__).resolve().parents[2]
INPUT = SUITE_ROOT / "sim_environment" / "data" / "processed" / "hipparcos_vmag6.bin"
OUTPUT = SUITE_ROOT / "flight_software" / "src" / "hipparcos_catalog.cpp"


def cpp_float(value: np.float32) -> str:
    literal = f"{float(value):.9g}"
    if "." not in literal and "e" not in literal.lower():
        literal += ".0"
    return literal + "F"


def main() -> None:
    with INPUT.open("rb") as binary:
        magic, count, record_size = struct.unpack(
            HEADER_FORMAT, binary.read(struct.calcsize(HEADER_FORMAT))
        )
        if magic != MAGIC or record_size != RECORD_DTYPE.itemsize:
            raise ValueError("Unsupported binary catalog format")
        records = np.fromfile(binary, dtype=RECORD_DTYPE, count=count)

    if len(records) != count:
        raise ValueError("Binary catalog is truncated")

    lines = [
        "// Generated by sim_environment/src/generate_cpp_catalog.py.",
        '#include "star_tracker/hipparcos_catalog.hpp"',
        "",
        "namespace star_tracker {",
        "",
        "const LisGridMatcher::Catalog kHipparcosCatalog = {{",
    ]
    lines.extend(
        "    {%dU, %s, %s, %s, %s},"
        % (
            record["star_id"],
            cpp_float(record["x"]),
            cpp_float(record["y"]),
            cpp_float(record["z"]),
            cpp_float(record["vmag"]),
        )
        for record in records
    )
    lines.extend(["}};", "", "}  // namespace star_tracker", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"Wrote {count:,} static catalog records to {OUTPUT}")


if __name__ == "__main__":
    main()
